GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6449667a2f9b67f76028792d

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Postman is good in testing backend",
  "important": false
}

###
PUT http://localhost:3001/api/notes/6449667a2f9b67f76028792d
Content-Type: application/json

{
  "content": "HTML is Easy-ish",
  "important": false
}

###
DELETE http://localhost:3001/api/notes/644b5ac84ca981483eeea8d3