GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6449667a2f9b67f76028792d

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Node for backend",
  "important": false
}

###
PUT http://localhost:3001/api/notes/6449667a2f9b67f76028792d
Content-Type: application/json

{
  "content": "HTML is Easy",
  "important": false
}

###
DELETE http://localhost:3001/api/notes/644f5684138701b1f8673b7c